In [1]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d camnugent/california-housing-prices

Dataset URL: https://www.kaggle.com/datasets/camnugent/california-housing-prices
License(s): CC0-1.0
Downloading california-housing-prices.zip to /content
  0% 0.00/400k [00:00<?, ?B/s]
100% 400k/400k [00:00<00:00, 59.2MB/s]

In [2]:
!unzip california-housing-prices.zip

Archive:  california-housing-prices.zip
  inflating: housing.csv

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('housing.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
df_shuffled = df.sample(n=len(df),random_state=1)

In [6]:
df_shuffled.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
4712,-118.36,34.06,39.0,2810.0,670.0,1109.0,624.0,3.2500,355000.0,<1H OCEAN
2151,-119.78,36.78,37.0,2185.0,455.0,1143.0,438.0,1.9784,70700.0,INLAND
15927,-122.42,37.73,46.0,1819.0,411.0,1534.0,406.0,4.0132,229400.0,NEAR BAY
82,-122.28,37.81,52.0,340.0,97.0,200.0,87.0,1.5208,112500.0,NEAR BAY
8161,-118.13,33.82,37.0,1530.0,290.0,711.0,283.0,5.1795,225400.0,<1H OCEAN

In [7]:
pd.get_dummies(df_shuffled['ocean_proximity'])

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
4712        True   False   False     False       False
2151       False    True   False     False       False
15927      False   False   False      True       False
82         False   False   False      True       False
8161        True   False   False     False       False
...          ...     ...     ...       ...         ...
10955       True   False   False     False       False
17289       True   False   False     False       False
5192        True   False   False     False       False
12172      False    True   False     False       False
235        False   False   False      True       False

[20640 rows x 5 columns]

In [8]:
df_shuffled.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
4712,-118.36,34.06,39.0,2810.0,670.0,1109.0,624.0,3.2500,355000.0,<1H OCEAN
2151,-119.78,36.78,37.0,2185.0,455.0,1143.0,438.0,1.9784,70700.0,INLAND
15927,-122.42,37.73,46.0,1819.0,411.0,1534.0,406.0,4.0132,229400.0,NEAR BAY
82,-122.28,37.81,52.0,340.0,97.0,200.0,87.0,1.5208,112500.0,NEAR BAY
8161,-118.13,33.82,37.0,1530.0,290.0,711.0,283.0,5.1795,225400.0,<1H OCEAN

In [9]:
df_shuffled.drop('ocean_proximity',axis=1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
4712,-118.36,34.06,39.0,2810.0,670.0,1109.0,624.0,3.2500,355000.0
2151,-119.78,36.78,37.0,2185.0,455.0,1143.0,438.0,1.9784,70700.0
15927,-122.42,37.73,46.0,1819.0,411.0,1534.0,406.0,4.0132,229400.0
82,-122.28,37.81,52.0,340.0,97.0,200.0,87.0,1.5208,112500.0
8161,-118.13,33.82,37.0,1530.0,290.0,711.0,283.0,5.1795,225400.0
...,...,...,...,...,...,...,...,...,...
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,205300.0
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,104800.0
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,140700.0
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,126000.0

In [10]:
df_final = pd.concat([df_shuffled.drop('ocean_proximity',axis=1),pd.get_dummies(df_shuffled['ocean_proximity'])],axis=1)

In [11]:
df_final

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
4712,-118.36,34.06,39.0,2810.0,670.0,1109.0,624.0,3.2500,355000.0,True,False,False,False,False
2151,-119.78,36.78,37.0,2185.0,455.0,1143.0,438.0,1.9784,70700.0,False,True,False,False,False
15927,-122.42,37.73,46.0,1819.0,411.0,1534.0,406.0,4.0132,229400.0,False,False,False,True,False
82,-122.28,37.81,52.0,340.0,97.0,200.0,87.0,1.5208,112500.0,False,False,False,True,False
8161,-118.13,33.82,37.0,1530.0,290.0,711.0,283.0,5.1795,225400.0,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,205300.0,True,False,False,False,False
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,True,False,False,False,False
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,104800.0,True,False,False,False,False
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,140700.0,False,True,False,False,False
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,126000.0,False,False,False,True,False

In [12]:
df_final.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY',
       'NEAR OCEAN'],
      dtype='object')

In [13]:
df_final = df_final[['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income', '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY',
       'NEAR OCEAN',
       'median_house_value']]

In [14]:
df_final

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,median_house_value
4712,-118.36,34.06,39.0,2810.0,670.0,1109.0,624.0,3.2500,True,False,False,False,False,355000.0
2151,-119.78,36.78,37.0,2185.0,455.0,1143.0,438.0,1.9784,False,True,False,False,False,70700.0
15927,-122.42,37.73,46.0,1819.0,411.0,1534.0,406.0,4.0132,False,False,False,True,False,229400.0
82,-122.28,37.81,52.0,340.0,97.0,200.0,87.0,1.5208,False,False,False,True,False,112500.0
8161,-118.13,33.82,37.0,1530.0,290.0,711.0,283.0,5.1795,True,False,False,False,False,225400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10955,-117.88,33.76,17.0,1768.0,474.0,1079.0,436.0,1.7823,True,False,False,False,False,205300.0
17289,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,True,False,False,False,False,500001.0
5192,-118.26,33.93,42.0,1433.0,295.0,775.0,293.0,1.1326,True,False,False,False,False,104800.0
12172,-117.16,33.73,10.0,2381.0,454.0,1323.0,477.0,2.6322,False,True,False,False,False,140700.0
235,-122.20,37.79,35.0,1802.0,459.0,1009.0,390.0,2.3036,False,False,False,True,False,126000.0

In [15]:
df_final.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
<1H OCEAN               0
INLAND                  0
ISLAND                  0
NEAR BAY                0
NEAR OCEAN              0
median_house_value      0
dtype: int64

In [16]:
df_final = df_final.dropna()
len(df_final)

20433

In [17]:
df_final.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
<1H OCEAN             0
INLAND                0
ISLAND                0
NEAR BAY              0
NEAR OCEAN            0
median_house_value    0
dtype: int64

In [18]:
train , valid, test = np.split(df_final.sample(frac=1),[int(0.6*len(df_final)),int(0.8*len(df_final))])

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [19]:
len(train),len(valid),len(test)

(12259, 4087, 4087)

In [20]:
x_train,y_train = train.to_numpy()[:,:-1],train.to_numpy()[:,-1]
x_val,y_val = valid.to_numpy()[:,:-1],valid.to_numpy()[:,-1]
x_test,y_test = test.to_numpy()[:,:-1],test.to_numpy()[:,-1]

In [21]:
x_train,y_train

(array([[-117.43, 33.93, 15.0, ..., False, False, False],
        [-118.37, 34.23, 32.0, ..., False, False, False],
        [-118.33, 33.77, 33.0, ..., False, False, True],
        ...,
        [-122.02, 37.31, 34.0, ..., False, False, False],
        [-118.15, 34.03, 43.0, ..., False, False, False],
        [-118.39, 34.05, 42.0, ..., False, False, False]], dtype=object),
 array([129300.0, 164600.0, 500001.0, ..., 341400.0, 158800.0, 500001.0],
       dtype=object))

In [22]:
x_train.shape,y_train.shape

((12259, 13), (12259,))

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler().fit(x_train[:, :8])

In [26]:
def preprocessor(X):
  A = np.copy(X)
  A[:, :8] = scaler.transform(A[:, :8])
  return A

In [40]:
x_train, x_val, x_test = preprocessor(x_train), preprocessor(x_val), preprocessor(x_test)

In [41]:
x_train.shape,y_train.shape

((12259, 13), (12259,))

In [42]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.linear_model import LinearRegression

In [47]:
lm = LinearRegression().fit(x_train,y_train)
y_train_pred = lm.predict(x_train)
y_val_pred = lm.predict(x_val)

In [48]:
mse(y_train_pred,y_train,squared = False),mse(y_val_pred,y_val,squared = False)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

(69338.35501625312, 65431.753398535366)

In [49]:
from sklearn.neighbors import KNeighborsRegressor

In [60]:
knn = KNeighborsRegressor(n_neighbors=11).fit(x_train,y_train)
y_train_pred_knn = knn.predict(x_train)
y_val_pred_knn = knn.predict(x_val)

In [61]:
mse(y_train_pred_knn,y_train,squared = False),mse(y_val_pred_knn,y_val,squared = False)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

(55493.8309426186, 59005.38604789751)

In [62]:
from sklearn.ensemble import RandomForestRegressor

In [67]:
rfr = RandomForestRegressor(max_depth=8).fit(x_train,y_train)
y_train_pred_rfr = rfr.predict(x_train)
y_val_pred_rfr = rfr.predict(x_val)

In [68]:
mse(y_train_pred_rfr,y_train,squared = False),mse(y_val_pred_rfr,y_val,squared = False)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

(52292.70911688652, 55268.740605188825)

In [69]:
from sklearn.ensemble import GradientBoostingRegressor

In [78]:
gbr = GradientBoostingRegressor(n_estimators = 290).fit(x_train, y_train)
y_train_pred_gbr = gbr.predict(x_train)
y_val_pred_gbr = gbr.predict(x_val)

In [79]:
mse(y_train_pred_gbr,y_train,squared = False),mse(y_val_pred_gbr,y_val,squared = False)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

(45020.708799585256, 48623.970124342966)